security:


    providers:
        our_db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login
            logout:
                path: user_logout
                target: accueil

    encoders:
        App\Entity\User:
            algorithm: bcrypt


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/sortie, roles: ROLE_USER }
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

